# AI-6 Chainlit Configuration File
default_model_id: "gpt-oss:20b"
tools_dirs: ["${HOME}/git/ai-six/py/backend/tools"]
mcp_tools_dirs: ["${HOME}/git/ai-six/py/backend/mcp_tools"]
memory_dir: "${HOME}/git/ai-six/memory/chainlit"
checkpoint_interval: 3

# Provider configuration
provider_config:
  openai:
    api_key: ${OPENAI_API_KEY}
    default_model: "gpt-4o"
  ollama:
    model: "qwen2.5-coder:32b"

# Tool configuration
tool_config:
  claude:
    api_key: ${ANTHROPIC_API_KEY}

# Tool filtering (at most one can be specified):
# enabled_tools: ["git", "ls", "cat"]  # Only allow these tools
# disabled_tools: ["rm", "mv"]         # Disable these tools
