name: Run Tests on Backend Changes

on:
  pull_request:
    paths:
      - 'py/backend/**'
  push:
    branches:
      - main
    paths:
      - 'py/backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Specify the python version

    - name: Install dependencies
      working-directory: py
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      working-directory: py
      run: |
        python -m unittest discover -s backend/tests
