name: Build and Publish Python Package

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for version detection

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install

    - name: Build package
      run: |
        cd py/
        uv build

    - name: Check package
      run: |
        cd py/
        uv run twine check dist/*

    - name: Publish to PyPI
      run: |
        cd py/
        uv publish --token ${{ secrets.PYPI_API_TOKEN }}

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          ## Changes
          - See commit history for detailed changes

          ## Installation
          ```bash
          pip install ai-six
          ```